'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
// Local crossfades keep selection immediate and cancellable, including rapid taps.
const swaps=new WeakMap();
function seamless(region,update,options={}){
 const previous=swaps.get(region);if(previous){previous.animations.forEach(a=>a.cancel());previous.clone.remove();swaps.delete(region)}
 const reduced=document.body.classList.contains('motion-off')||matchMedia('(prefers-reduced-motion: reduce)').matches;
 if(reduced||!region.animate||!region.getBoundingClientRect().width){update();return}
 const rect=options.rect||region.getBoundingClientRect();let parent=region.parentElement;while(parent&&getComputedStyle(parent).display==='contents')parent=parent.parentElement;const base=options.base||parent.getBoundingClientRect();
 const clone=region.cloneNode(true);clone.removeAttribute('id');clone.querySelectorAll('[id]').forEach(x=>x.removeAttribute('id'));clone.setAttribute('aria-hidden','true');clone.inert=true;
 if(getComputedStyle(parent).position==='static')parent.style.position='relative';
 Object.assign(clone.style,{position:'absolute',left:(rect.left-base.left+parent.scrollLeft)+'px',top:(rect.top-base.top+parent.scrollTop)+'px',width:rect.width+'px',height:rect.height+'px',margin:'0',pointerEvents:'none',zIndex:'4'});
 const computed=getComputedStyle(region);for(const property of ['fontSize','fontFamily','fontWeight','fontStyle','lineHeight','letterSpacing','color','whiteSpace','fontFeatureSettings','fontKerning','textRendering'])clone.style[property]=computed[property];if(region.id==='hero-title')clone.querySelectorAll('em').forEach(x=>x.style.fontStyle='normal');update();parent.append(clone);

 const outgoing=clone.animate([{opacity:1,transform:'translateY(0)'},{opacity:0,transform:'translateY(-3px)'}],{duration:options.hero?190:105,easing:'ease-out',fill:'both'});
 const incoming=region.animate([{opacity:0,transform:'translateY(4px)'},{opacity:1,transform:'translateY(0)'}],{duration:options.hero?450:245,delay:options.hero?170:85,easing:'cubic-bezier(.2,.7,.25,1)',fill:'both'});
 const animations=[outgoing,incoming];const item={clone,animations};swaps.set(region,item);
 Promise.allSettled(item.animations.map(a=>a.finished)).then(()=>{if(swaps.get(region)!==item)return;clone.remove();item.animations.forEach(a=>a.cancel());swaps.delete(region)});
}
// Capture only changing text; controls and persistent product information stay fixed.
function textTransition(elements,update){const snapshots=elements.map(el=>{let parent=el.parentElement;while(parent&&getComputedStyle(parent).display==='contents')parent=parent.parentElement;return{el,html:el.innerHTML,rect:el.getBoundingClientRect(),base:parent.getBoundingClientRect()}});update();for(const {el,html,rect,base} of snapshots){if(html===el.innerHTML)continue;const next=el.innerHTML;el.innerHTML=html;seamless(el,()=>el.innerHTML=next,{hero:!!el.closest('.product-intro'),rect,base})}}
window.aoeTextTransition=textTransition;
window.aoeSeamless=seamless;
const products={wash:{name:'Boost Facial Wash',category:'01 / 洗う',image:'assets/wash-front.jpg',desc:'ハトムギ種子エキスとクレイを配合した泡の洗顔料。肌への関心から3タイプを選べます。',spec:[['容量','100 g'],['税込価格','PINK・YELLOW ¥2,590 / BLUE ¥2,750'],['香り・容器','微香料 / パウチチューブ'],['製造国','日本']],use:['さくらんぼ半分ほどを目安に取り、ネットで泡立てます。','泡で顔全体を洗い、洗い流します。','泡パックとして使う場合は、公式の使用方法・注意事項をご確認ください。'],texture:'公式が案内する使用感：しっかりとした泡で洗うタイプ。',value:'使用量に幅があるため、1本の使用回数は断定していません。',url:'https://store.aoeweb.link/product/detail/3'},serum:{name:'Booster Serum',category:'02 / 整える',image:'assets/serum-front.jpg',desc:'リポソームと発酵成分を組み合わせた導入美容液。セラミドAP・NG・NPを配合。AGING CAREとBRIGHTENINGの2タイプ。',spec:[['容量','30 ml'],['税込価格','¥4,995'],['香り・容器','無香料 / ポンプタイプ'],['製造国','日本']],use:['洗顔を終えたら、化粧水より先に使います。','2〜3プッシュを目安に手に取り、顔になじませます。','そのあと、いつもの化粧水や美容液を使います。'],texture:'公式が案内する使用感：粘度を抑えた、さらりとしたテクスチャー。',value:'1回の量には個人差があります。使用回数や効果の持続時間は断定していません。',url:'https://store.aoeweb.link/product/detail/33'},eye:{name:'Under Eye Mask',category:'03 / いたわる',image:'assets/eye-front.jpg',desc:'海藻を原料とするハイドロゲルの目元用シート。AGINGCARE・BRIGHTENING・CIRCULATIONの3タイプ。2024年サステナブルコスメアワードの審査員賞・生物多様性部門を受賞。',spec:[['内容量','60枚'],['税込価格','¥7,480'],['香り・容器','無香料 / スクリュータイプ'],['製造国','日本']],use:['いつものスキンケアを終えてから、清潔なスパチュラなどで取り出します。','目元に密着させます。公式は2時間以上の貼付を案内しています。','シートをやさしくはがします。使用時間・肌の状態は公式の注意事項をご確認ください。'],texture:'公式が案内する使用感：しっとりとした貼り心地のウォータースキンシート。',value:'両目に1枚ずつなら30回分。1回約249円（7,480円÷30回、送料別）。',url:'https://store.aoeweb.link/product/detail/25'}};
window.aoeProducts=products;
let previousFocus=null,selected='eye';
function openDialog(d){previousFocus=document.activeElement;d.showModal();d.querySelector('.dialog-close').focus()}
function showProduct(key){const p=products[key];$('#dialog-title').textContent=p.name;$('#dialog-category').textContent=p.category;$('#dialog-desc').textContent=p.desc;$('#dialog-image').src=p.image;$('#dialog-image').alt=p.name+' 提供された商品写真';$('#dialog-link').href=p.url;$('#dialog-spec').replaceChildren(...p.spec.map(([a,b])=>{const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=a;dd.textContent=b;row.append(dt,dd);return row}));$('#dialog-use').replaceChildren(...p.use.map(s=>{const li=document.createElement('li');li.textContent=s;return li}));$('#dialog-texture').textContent=p.texture;$('#dialog-value').textContent=p.value;openDialog($('#product-dialog'))}
window.showProduct=showProduct;
$$('[data-detail]').forEach(b=>b.addEventListener('click',()=>showProduct(b.dataset.detail)));
window.addEventListener('product-selected',e=>{selected=e.detail;const p=products[selected];textTransition([$('#dock-name'),$('#dock-price')],()=>{$('#dock-name').replaceChildren(document.createTextNode(p.name+' '));const small=document.createElement('small');small.textContent={eye:'60枚',serum:'30 ml',wash:'100 g / '+$('#wash-type').value.toUpperCase()}[selected];$('#dock-name').append(small);$('#dock-price').textContent={eye:'¥7,480',serum:'¥4,995',wash:$('#wash-type').value==='blue'?'¥2,750':'¥2,590'}[selected];$('#dock-buy').href=p.url;});});
$('#dock-detail').addEventListener('click',()=>showProduct(selected));
$$('[data-explore]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.explore==='wash')window.product3D?.setWashType($('#wash-type').value);window.product3D?.select(b.dataset.explore);$('#home').scrollIntoView({behavior:document.body.classList.contains('motion-off')?'instant':'smooth'})}));
$$('dialog').forEach(d=>{d.querySelector('.dialog-close').addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target!==d)return;const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()});d.addEventListener('close',()=>previousFocus?.focus())});
$('#sources-open').addEventListener('click',()=>openDialog($('#sources-dialog')));$('#model-info').addEventListener('click',()=>openDialog($('#model-dialog')));$('#feedback-open').addEventListener('click',()=>openDialog($('#feedback-dialog')));
const rituals=[['スキンケアを終えてから。','清潔なスパチュラなどでシートを取り出します。乳液やクリームを使う場合も、そのあとに。'],['目元に、そっと重ねる。','目元に密着させて使います。公式は2時間以上の貼付を案内しています。肌の状態を見ながら、詳しい注意事項もご確認ください。'],['やさしく、はがす。','シートをやさしくはがします。肌に異常を感じた場合は使用を中止し、公式の使用上の注意をご確認ください。']];
$$('[data-ritual]').forEach(b=>b.addEventListener('click',()=>{$$('[data-ritual]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));const r=rituals[Number(b.dataset.ritual)];seamless($('.ritual-reading'),()=>{$('#ritual-title').textContent=r[0];$('#ritual-text').textContent=r[1]})}));
// Named photograph transitions retain the actual layout geometry; no gallery clones.
let catalogTransition=null,catalogToken=0;const catalogStyles=document.createElement('style');document.head.append(catalogStyles);
function switchCatalog(key){const token=++catalogToken;catalogTransition?.skipTransition();const gallery=$('.product-cards');const cards=[...gallery.querySelectorAll('[data-card]')];const copyRects=cards.map(c=>c.querySelector('.card-content').getBoundingClientRect());const update=()=>{if(token!==catalogToken)return;cards.forEach(x=>x.hidden=key!=='all'&&x.dataset.card!==key);gallery.classList.toggle('is-focused',key!=='all');catalogStyles.textContent=cards.filter(c=>!c.hidden).map(c=>{const old=copyRects[cards.indexOf(c)],next=c.querySelector('.card-content').getBoundingClientRect(),name='care-copy-'+c.dataset.card;return old.width?`::view-transition-old(${name}){width:${old.width}px;height:${old.height}px;transform:translate(${old.left-next.left}px,${old.top-next.top}px)}`:''}).join('')};const reduced=document.body.classList.contains('motion-off')||matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduced){update();return}if(document.startViewTransition){catalogTransition=document.startViewTransition(update);catalogTransition.ready.catch(()=>{});catalogTransition.updateCallbackDone.catch(()=>{});catalogTransition.finished.catch(()=>{}).finally(()=>{if(token===catalogToken){catalogTransition=null;catalogStyles.textContent=''}});return}const photographs=cards.map(c=>c.querySelector('.card-photo'));const before=photographs.map(x=>{x.getAnimations().forEach(a=>a.cancel());return x.getBoundingClientRect()});update();photographs.forEach((photo,i)=>{if(cards[i].hidden)return;const next=photo.getBoundingClientRect(),old=before[i];photo.animate(old.width?[{transform:`translate(${old.left-next.left}px,${old.top-next.top}px) scale(${old.width/next.width},${old.height/next.height})`,transformOrigin:'0 0'},{transform:'none',transformOrigin:'0 0'}]:[{opacity:0},{opacity:1}],{duration:560,easing:'cubic-bezier(.22,.68,.25,1)'});cards[i].querySelector('.card-content').animate([{opacity:0},{opacity:1}],{duration:320,delay:100,fill:'backwards'})})}
const goals={all:'洗顔、美容液、目元ケア。それぞれを、いつものケアに。',wash:'洗顔から見直したい方へ。PINK・BLUE・YELLOWの選び方を確認できます。',serum:'洗顔のあと、化粧水の前に。さらりとした導入美容液。',eye:'いつものケアの最後に。目元に重ねるシートを選ぶ。'};
$$('[data-goal]').forEach(b=>b.addEventListener('click',()=>{const key=b.dataset.goal;$$('[data-goal]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));switchCatalog(key);seamless($('#goal-copy'),()=>$('#goal-copy').textContent=goals[key])}));
$('#wash-type').addEventListener('change',e=>{seamless($('#wash-price'),()=>$('#wash-price').textContent='100 g / '+(e.target.value==='blue'?'¥2,750':'¥2,590')+'（税込）');window.product3D?.setWashType(e.target.value)});
const mats={hydrogel:{role:'シートをつくる素材',name:'カラギーナン',origin:'紅藻類 / インドネシア',product:'Under Eye Mask',desc:'紅藻類を原料とし、目元用シートの形をつくる成分。自然の素材を、肌に重ねられるかたちへ。',key:'eye'},clay:{role:'洗うケアの素材',name:'クレイ',origin:'カオリン / アメリカ\nベントナイト・海シルト / 日本',product:'Boost Facial Wash',desc:'洗顔料に組み合わせたクレイ。古い角質や余分な皮脂を洗い流す、泡のケアを支えます。',key:'wash'},herb:{role:'保湿のための素材',name:'ハトムギ種子エキス',origin:'ハトムギ / 日本',product:'Boost Facial Wash',desc:'洗顔料に配合したハトムギ種子エキス。公式では保湿成分として用途を公開しています。',key:'wash'}};
$$('[data-material]').forEach(b=>b.addEventListener('click',()=>{$$('[data-material]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));const m=mats[b.dataset.material];seamless($('.material-detail'),()=>{$('#material-role').textContent=m.role;$('#material-name').textContent=m.name;$('#material-description').textContent=m.desc;$('#material-origin').textContent=m.origin;$('#material-product').textContent=m.product;$('#material-source').href=products[m.key].url;$('.nature').dataset.material=b.dataset.material})}));
$('#mobile-menu').addEventListener('click',()=>{const open=$('nav').classList.toggle('menu-open');$('#mobile-menu').setAttribute('aria-expanded',String(open))});$$('nav a').forEach(a=>a.addEventListener('click',()=>{$('nav').classList.remove('menu-open');$('#mobile-menu').setAttribute('aria-expanded','false')}));
const reduce=matchMedia('(prefers-reduced-motion: reduce)');let motion=!reduce.matches;
function updateMotion(){document.body.classList.toggle('motion-off',!motion);$('#motion-toggle').textContent=motion?'Motion on':'Motion off';$('#motion-toggle').setAttribute('aria-pressed',String(motion));window.dispatchEvent(new Event('motion-changed'))}$('#motion-toggle').addEventListener('click',()=>{motion=!motion;updateMotion()});reduce.addEventListener('change',()=>{motion=!reduce.matches;updateMotion()});updateMotion();
new IntersectionObserver(e=>$('.purchase-dock').classList.toggle('visible',!e[0].isIntersecting),{threshold:0}).observe($('#home'));
const form=$('#feedback-form'),status=$('#feedback-status');const feedbackKey='aoe-concept-feedback-v6';
try{const saved=JSON.parse(localStorage.getItem(feedbackKey)||'null');if(saved)for(const key of ['remember','interest','difference'])form.elements[key].value=saved[key]||''}catch{}
function feedbackData(){return{...Object.fromEntries(new FormData(form)),version:'a.o.e concept v6',savedAt:new Date().toISOString()}}
form.addEventListener('submit',e=>{e.preventDefault();try{localStorage.setItem(feedbackKey,JSON.stringify(feedbackData()));status.textContent='この端末に下書きを保存しました。送信は行っていません。'}catch{status.textContent='この環境では保存できません。回答をダウンロードできます。'}});
$('#feedback-export').addEventListener('click',()=>{const data=feedbackData();const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='aoe-feedback-v6.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status.textContent='回答ファイルを書き出しました。'});$('#feedback-clear').addEventListener('click',()=>{try{localStorage.removeItem(feedbackKey)}catch{}form.reset();status.textContent='下書きを消去しました。'});

// Actual formula photographs remain in place while the chosen formula changes.
function syncFormula(key,value){$$(`[data-formula="${key}"]`).forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.value===value)))}
$$('[data-formula]').forEach(b=>b.addEventListener('click',()=>{const select=$('#'+b.dataset.formula+'-type');select.value=b.dataset.value;select.dispatchEvent(new Event('change',{bubbles:true}))}));
$('#eye-type').addEventListener('change',e=>syncFormula('eye',e.target.value));
$('#wash-type').addEventListener('change',e=>syncFormula('wash',e.target.value));

// Scroll only schedules one optical update; no persistent render loop or layout writes.
(()=>{const panels=[document.querySelector('header'),document.querySelector('.object-selection'),document.querySelector('.purchase-dock'),document.querySelector('.material-nav'),...document.querySelectorAll('.object-tools button')].filter(Boolean);panels.forEach(p=>p.classList.add('optical-glass'));let pending=0;const update=()=>{pending=0;const y=scrollY,h=innerHeight,reduced=document.body.classList.contains('motion-off')||matchMedia('(prefers-reduced-motion: reduce)').matches;const rectangles=panels.map(p=>p.getBoundingClientRect());panels.forEach((p,i)=>{const r=rectangles[i];if(!r.width||r.bottom<0||r.top>h)return;const phase=reduced?.5:Math.max(0,Math.min(1,(h-r.top)/(h+r.height))),wave=reduced?0:Math.sin(y*.0014+i*.75);p.style.setProperty('--glass-angle',(112+phase*36+wave*8)+'deg');p.style.setProperty('--glass-x',(20+phase*48+wave*9)+'%');p.style.setProperty('--glass-y',(12+phase*65)+'%');const cosAngle=Math.cos((.25+phase*.7)*Math.PI/2),fresnel=.04+.96*Math.pow(1-cosAngle,5);p.style.setProperty('--glass-edge',String(.34+fresnel*.36));p.style.setProperty('--glass-reflection',(28+phase*40+wave*5)+'%')})};const schedule=()=>{if(!pending)pending=requestAnimationFrame(update)};addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule,{passive:true});addEventListener('motion-changed',schedule);document.addEventListener('visibilitychange',()=>{if(!document.hidden)schedule()});schedule()})();
